### ISSUE TITLE
ValueError: Dimensions must be equal, but are 1024 and 1025 for 'Add_2' (op: 'Add') with input sha pes: [?,1024], [1025].

### ISSUE THREAD

**Issue by jochne** [jmcjacob/EmotionClassifier#1]
ValueError: Dimensions must be equal, but are 1024 and 1025 for 'Add_2' (op: 'Add') with input sha
pes: [?,1024], [1025].

**Comment by jmcjacob** [comment]
Fixed sorry about that.
